In [3]:
import numpy as np

a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
a.shape

(3,)

In [5]:
a.ndim

1

In [6]:
a.dtype

dtype('int32')

In [7]:
a.itemsize

4

In [8]:
a.size

3

In [11]:
a = np.array([1, 2, 3], dtype='int32')
b = np.array([4, 5, 6], dtype='int64')
a.dtype

dtype('int32')

In [12]:
b.dtype

dtype('int64')

In [14]:
c = a + b
print(c)

[5 7 9]


In [15]:
c.dtype

dtype('int64')

In [19]:
a = np.array(range(10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
b = np.array([i for i in range(10) if i % 2 == 0])
b

array([0, 2, 4, 6, 8])

In [21]:
b.shape

(5,)

In [22]:
b.size

5

In [23]:
b.itemsize

4

In [24]:
b.dtype

dtype('int32')

In [25]:
b.ndim

1

In [26]:
a.max()

9

In [27]:
a.min()

0

In [28]:
a.mean()

4.5

In [29]:
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a = np.array([1,2,3])
b = np.array([[4,5,6],[7,8,9]])
c = np.append(a,b)
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
c.ndim

1

In [52]:
b.ndim

2

In [53]:
np.append([a],b,axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
np.random.rand(3,3)

array([[0.03830141, 0.41042989, 0.78176349],
       [0.3289709 , 0.18395383, 0.68265595],
       [0.15121586, 0.59359454, 0.18546914]])

In [55]:
np.random.randint(0,10,size=10)

array([0, 3, 6, 3, 1, 8, 1, 7, 3, 2])

## lab 11-2

In [60]:
a = np.array([23, 45, 67, 7, 2, 30, 34, 82])
print(f'a = array({a})')

a = array([23 45 67  7  2 30 34 82])


In [61]:
print(f'최댓값 : {a.max()}')

최댓값 : 82


In [62]:
print(f'최솟값 : {a.min()}')

최솟값 : 2


In [63]:
print(f'평균값 : {a.mean()}')

평균값 : 36.25


In [64]:
b = np.random.randint(0, 100, size=10)
print(f'b = {b}')
print(f'max : {b.max()}')
print(f'min : {b.min()}')
print(f'meaan : {b.mean()}')

b = [47 57 65 24 10 98 35 61 35 53]
max : 98
min : 10
meaan : 48.5


In [67]:
c = np.append(a, b)
print(f'c = {c}')

c = [23 45 67  7  2 30 34 82 47 57 65 24 10 98 35 61 35 53]


## ndarray의 연산

In [69]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b

array([5, 7, 9])

In [70]:
a = np.array([1,2])
b = np.array([4,5,6])
a + b

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [74]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a @ b

array([[19, 22],
       [43, 50]])

In [75]:
np.matmul(a,b)

array([[19, 22],
       [43, 50]])

## Lab 11-3 다차원 행렬의 생성과 활용

In [98]:
a = np.array(range(1,10))
a.shape = (3,3)
print(f'a = {a}')

a = [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [105]:
b = np.array([2]*9)
b.shape = (3,3)
print(f'b = {b}')

b = [[2 2 2]
 [2 2 2]
 [2 2 2]]


In [106]:
a + b

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [107]:
a - b

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [109]:
a * b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [110]:
a / b

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [111]:
a @ b

array([[12, 12, 12],
       [30, 30, 30],
       [48, 48, 48]])

In [112]:
a ** 2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

## ndarray의 생성

In [113]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [114]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [115]:
np.zeros(2,3)

TypeError: data type not understood

In [116]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [117]:
np.full((2,3),50)

array([[50, 50, 50],
       [50, 50, 50]])

In [118]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [120]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [121]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

## Lab 11-4

In [124]:
a1 = np.full((3, 3), 2)
print(f'a1 = {a1}')

a1 = [[2 2 2]
 [2 2 2]
 [2 2 2]]


In [125]:
a2 = np.arange(1, 13)
print(f'a2 = {a2}')

a2 = [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [136]:
a3 = np.arange(1, 51)
print(f'a3 = {a3[a3 % 3 == 0]}')

a3 = [ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]


In [135]:
a33 = np.arange(3,51,3)
print(f'a33 = {a33}')

a33 = [ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]


In [139]:
a4 = np.linspace(0, 20, 5)
print(f'a4 = {a4}')

a4 = [ 0.  5. 10. 15. 20.]


In [140]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [141]:
np.arange(0, 24).reshape(4, 3, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

## Lab 11-5

In [143]:
a1 = np.arange(1,13).reshape(2,6)
print(f'a1 = {a1}')

a1 = [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [145]:
a2 = np.arange(1,31).reshape(3,10)
print(f'a2 = {a2}')

a2 = [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


In [147]:
a3 = a2.reshape(6,5)
print(f'a3 = {a3}')

a3 = [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [148]:
a4 = np.transpose(a3)
print(f'a4 = {a4}')

a4 = [[ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]
 [ 5 10 15 20 25 30]]


## 다차원 배열의 축

In [149]:
a = np.arange(0,6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [150]:
a.sum()

15

In [151]:
a.sum(axis=0)

array([6, 9])

In [152]:
a.max(axis=0)

array([4, 5])

In [153]:
a.max(axis=1)

array([1, 3, 5])

In [155]:
a = np.arange(0,5)
a

array([0, 1, 2, 3, 4])

In [156]:
np.insert(a, 5, 5)

array([0, 1, 2, 3, 4, 5])

In [157]:
a = np.array([[1,2,3],[4,5,6]])
np.insert(a, 1, 4, axis=0)

array([[1, 2, 3],
       [4, 4, 4],
       [4, 5, 6]])

## Lab 11-6

In [159]:
a = np.random.randint(1, 100, size = 15).reshape(3,5)
print(f'a = {a}')

a = [[41 92 58 65 41]
 [ 2 19 66  8 30]
 [30 61 80 46 12]]


In [161]:
print(f'a의 열방향 최댓값 : {a.max(axis=0)}')
print(f'a의 열방향 최솟값 : {a.min(axis=0)}')
print(f'a의 열방향 평균값 : {a.mean(axis=0)}')

a의 열방향 최댓값 : [41 92 80 65 41]
a의 열방향 최솟값 : [ 2 19 58  8 12]
a의 열방향 평균값 : [24.33333333 57.33333333 68.         39.66666667 27.66666667]


In [162]:
print(f'a의 행방향 최댓값 : {a.max(axis=1)}')
print(f'a의 행방향 최솟값 : {a.min(axis=1)}')
print(f'a의 행방향 평균값 : {a.mean(axis=1)}')

a의 행방향 최댓값 : [92 66 80]
a의 행방향 최솟값 : [41  2 12]
a의 행방향 평균값 : [59.4 25.  45.8]


## Lab 11-7

In [166]:
a = np.arange(1,11)
b = a[1:9:2]
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[2 4 6 8]


In [168]:
b = a[5:]
c = a[6:]
d = a[:3]
e = a[::2]
f = a[::-2]
print(b)
print(c)
print(d)
print(e)
print(f)

[ 6  7  8  9 10]
[ 7  8  9 10]
[1 2 3]
[1 3 5 7 9]
[10  8  6  4  2]


## Lab 11-8

In [169]:
a = np.arange(0,24).reshape(4,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [179]:
print('index\t  element')
for index in np.ndindex(a.shape) :
    print(f'{index}   {a[index]}')

index	  element
(0, 0, 0)   0
(0, 0, 1)   1
(0, 1, 0)   2
(0, 1, 1)   3
(0, 2, 0)   4
(0, 2, 1)   5
(1, 0, 0)   6
(1, 0, 1)   7
(1, 1, 0)   8
(1, 1, 1)   9
(1, 2, 0)   10
(1, 2, 1)   11
(2, 0, 0)   12
(2, 0, 1)   13
(2, 1, 0)   14
(2, 1, 1)   15
(2, 2, 0)   16
(2, 2, 1)   17
(3, 0, 0)   18
(3, 0, 1)   19
(3, 1, 0)   20
(3, 1, 1)   21
(3, 2, 0)   22
(3, 2, 1)   23


In [180]:
np.concatenate((a[0,0], a[1,0]), axis=0)

array([0, 1, 6, 7])

In [181]:
np.concatenate((a[0,0], a[2,1]), axis=0)

array([ 0,  1, 14, 15])

In [182]:
np.concatenate((a[0],a[1]), axis=0)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [183]:
np.concatenate((a[0], a[1]), axis=1)

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

## 2차원 배열의 슬라이싱

In [184]:
a = np.arange(0, 9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [185]:
print(a[0])

[0 1 2]


In [186]:
print(a[0, :])

[0 1 2]


In [187]:
print(a[:, 0])

[0 3 6]


In [188]:
a[1, 1:].shape

(2,)

In [189]:
a[1:2, 1:].shape

(1, 2)

In [190]:
print(a[1, 1:])

[4 5]


In [191]:
print(a[1:2, 1:])

[[4 5]]


## Lab 11-9

In [192]:
a = np.arange(0,16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [194]:
b = a[:,1]
b

array([ 1,  5,  9, 13])

In [195]:
c = a[2, 1:]
c

array([ 9, 10, 11])

In [196]:
d = a[:2, :2]
d

array([[0, 1],
       [4, 5]])

In [197]:
e = a[1:3, 1:3]
e

array([[ 5,  6],
       [ 9, 10]])

In [198]:
f = a[:2, :3]
f.flatten()

array([0, 1, 2, 4, 5, 6])

In [199]:
g = a[2:, :].flatten()
g

array([ 8,  9, 10, 11, 12, 13, 14, 15])

In [200]:
h = np.append(a[1, 1:], a[3, 1:]).flatten()
h

array([ 5,  6,  7, 13, 14, 15])

## 선형 방정식 풀이, 행렬식

In [201]:
a = np.array([[2,3],[1,-2]])
b = np.array([1,4])
x = np.linalg.solve(a,b)
print(x)

[ 2. -1.]
